# Generated by Django 4.2.27 on 2026-01-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NurseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Anonymous', max_length=120)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='jobs.nurseprofile')),
            ],
        ),
    ]
