# Generated by Django 4.2.27 on 2026-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NurseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('symptoms_text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
